/* Auto-generated by generate_target_files.py from item2_target_bodies.py -- do not
 * hand-edit; edit item2_target_bodies.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `clk_enable_arm_pl011` (CCN 1). The real implementation is
 * compiled separately in clk_enable_arm_pl011.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_CLK_ENABLE_ARM_PL011_H_
#define AEROHARNESS_ITEM2_CLK_ENABLE_ARM_PL011_H_

#include "common_stubs.h"

int clk_enable_arm_pl011(const struct device *dev, uint32_t clk);

#endif /* AEROHARNESS_ITEM2_CLK_ENABLE_ARM_PL011_H_ */
