#!/usr/bin/env python3
"""
Generates, for each of the 18 item-2 targets, a `<name>.h` (forward declaration only,
parseable by the real, bug-fixed CASTExtractor for FunctionSignature extraction) and a
`<name>.c` (the real function body + any embedded real helper dependencies, with the
target function itself given external linkage so a separately-compiled harness.cpp can
call it). Idempotent -- re-run any time after editing target_definitions.py.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from target_definitions import TARGETS  # noqa: E402

OUT_DIR = Path(__file__).parent


def strip_static(body: str) -> str:
    """Removes a single leading 'static ' from a function body's return-type line."""
    if body.startswith("static "):
        return body[len("static "):]
    return body


def main() -> None:
    for t in TARGETS:
        h_path = OUT_DIR / f"{t.name}.h"
        c_path = OUT_DIR / f"{t.name}.c"

        h_content = f"""/* Auto-generated by generate_target_files.py from target_definitions.py -- do not
 * hand-edit; edit target_definitions.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `{t.name}` (CCN {t.ccn}). The real implementation is
 * compiled separately in {t.name}.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_{t.name.upper()}_H_
#define AEROHARNESS_ITEM2_{t.name.upper()}_H_

#include "common_stubs.h"

{t.signature}

#endif /* AEROHARNESS_ITEM2_{t.name.upper()}_H_ */
"""
        h_path.write_text(h_content, encoding="utf-8")

        helper_blocks = "\n\n".join(t.helpers)
        c_content = f"""/* Auto-generated by generate_target_files.py from target_definitions.py -- do not
 * hand-edit; edit target_definitions.py and re-run the generator instead.
 *
 * Real implementation of `{t.name}`, copied verbatim from
 * zephyr-src/drivers/serial/uart_pl011.c (re-verified against that file during
 * preparation, Oct 2 2026), with only the `static` keyword stripped from this one
 * function so a separately-compiled harness.cpp can call it. Any other function it
 * depends on is embedded below exactly as the real driver wrote it, kept `static`
 * (internal to this translation unit only, exactly matching the real driver's own
 * linkage for those helpers).
 */
#include "{t.name}.h"

/* Defines the mock_regs_ptr global declared `extern` in common_stubs.h. Exactly one
 * translation unit must define it; this .c file is always compiled alongside the
 * harness, so it is the natural, single place to do so. The LLM-authored harness.cpp
 * only needs to ASSIGN to it (mock_regs_ptr = &my_regs;) via the extern declaration it
 * already gets through common_stubs.h -- never declare or define it itself. */
volatile void *mock_regs_ptr;

{helper_blocks}

{strip_static(t.body)}
"""
        c_path.write_text(c_content, encoding="utf-8")
        print(f"wrote {h_path.name}, {c_path.name}")


if __name__ == "__main__":
    main()
