/* Auto-generated by generate_target_files.py from target_definitions.py -- do not
 * hand-edit; edit target_definitions.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `pl011_irq_rx_enable` (CCN 1). The real implementation is
 * compiled separately in pl011_irq_rx_enable.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_PL011_IRQ_RX_ENABLE_H_
#define AEROHARNESS_ITEM2_PL011_IRQ_RX_ENABLE_H_

#include "common_stubs.h"

void pl011_irq_rx_enable(const struct device *dev);

#endif /* AEROHARNESS_ITEM2_PL011_IRQ_RX_ENABLE_H_ */
