/* Auto-generated by generate_target_files.py from target_definitions.py -- do not
 * hand-edit; edit target_definitions.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `pl011_err_check` (CCN 5). The real implementation is
 * compiled separately in pl011_err_check.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_PL011_ERR_CHECK_H_
#define AEROHARNESS_ITEM2_PL011_ERR_CHECK_H_

#include "common_stubs.h"

int pl011_err_check(const struct device *dev);

#endif /* AEROHARNESS_ITEM2_PL011_ERR_CHECK_H_ */
