/* Auto-generated by generate_target_files.py from item2_target_bodies.py -- do not
 * hand-edit; edit item2_target_bodies.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `pl011_is_readable` (CCN 4). The real implementation is
 * compiled separately in pl011_is_readable.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_PL011_IS_READABLE_H_
#define AEROHARNESS_ITEM2_PL011_IS_READABLE_H_

#include "common_stubs.h"

bool pl011_is_readable(const struct device *dev);

#endif /* AEROHARNESS_ITEM2_PL011_IS_READABLE_H_ */
