/* Auto-generated by generate_target_files.py from item2_target_bodies.py -- do not
 * hand-edit; edit item2_target_bodies.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `pl011_fifo_fill` (CCN 3). The real implementation is
 * compiled separately in pl011_fifo_fill.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_PL011_FIFO_FILL_H_
#define AEROHARNESS_ITEM2_PL011_FIFO_FILL_H_

#include "common_stubs.h"

int pl011_fifo_fill(const struct device *dev, const uint8_t *tx_data, int len);

#endif /* AEROHARNESS_ITEM2_PL011_FIFO_FILL_H_ */
