/* Auto-generated by generate_target_files.py from target_definitions.py -- do not
 * hand-edit; edit target_definitions.py and re-run the generator instead.
 *
 * Real implementation of `pl011_set_baudrate`, copied verbatim from
 * zephyr-src/drivers/serial/uart_pl011.c (re-verified against that file during
 * preparation, Oct 2 2026), with only the `static` keyword stripped from this one
 * function so a separately-compiled harness.cpp can call it. Any other function it
 * depends on is embedded below exactly as the real driver wrote it, kept `static`
 * (internal to this translation unit only, exactly matching the real driver's own
 * linkage for those helpers).
 */
#include "pl011_set_baudrate.h"

/* Defines the mock_regs_ptr global declared `extern` in common_stubs.h. Exactly one
 * translation unit must define it; this .c file is always compiled alongside the
 * harness, so it is the natural, single place to do so. The LLM-authored harness.cpp
 * only needs to ASSIGN to it (mock_regs_ptr = &my_regs;) via the extern declaration it
 * already gets through common_stubs.h -- never declare or define it itself. */
volatile void *mock_regs_ptr;



int pl011_set_baudrate(const struct device *dev,
                   uint32_t clk, uint32_t baudrate)
{
    /* Avoiding float calculations, bauddiv is left shifted by 6 */
    uint64_t bauddiv = (((uint64_t)clk) << PL011_FBRD_WIDTH)
                / (baudrate * 16U);
    volatile struct pl011_regs *uart = get_uart(dev);

    if ((bauddiv < (1u << PL011_FBRD_WIDTH))
        || (bauddiv > (65535u << PL011_FBRD_WIDTH))) {
        return -EINVAL;
    }

    uart->ibrd = bauddiv >> PL011_FBRD_WIDTH;
    uart->fbrd = bauddiv & ((1u << PL011_FBRD_WIDTH) - 1u);

    barrier_dmem_fence_full();

    uart->lcr_h = uart->lcr_h;

    return 0;
}
