/* Auto-generated by generate_target_files.py from item2_target_bodies.py -- do not
 * hand-edit; edit item2_target_bodies.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `pl011_set_flow_control` (CCN 3). The real implementation is
 * compiled separately in pl011_set_flow_control.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_PL011_SET_FLOW_CONTROL_H_
#define AEROHARNESS_ITEM2_PL011_SET_FLOW_CONTROL_H_

#include "common_stubs.h"

void pl011_set_flow_control(const struct device *dev, bool rts, bool cts);

#endif /* AEROHARNESS_ITEM2_PL011_SET_FLOW_CONTROL_H_ */
