/* Auto-generated by generate_target_files.py from item2_target_bodies.py -- do not
 * hand-edit; edit item2_target_bodies.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `pl011_irq_tx_complete` (CCN 1). The real implementation is
 * compiled separately in pl011_irq_tx_complete.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_PL011_IRQ_TX_COMPLETE_H_
#define AEROHARNESS_ITEM2_PL011_IRQ_TX_COMPLETE_H_

#include "common_stubs.h"

int pl011_irq_tx_complete(const struct device *dev);

#endif /* AEROHARNESS_ITEM2_PL011_IRQ_TX_COMPLETE_H_ */
