/* Auto-generated by generate_target_files.py from item2_target_bodies.py -- do not
 * hand-edit; edit item2_target_bodies.py and re-run the generator instead.
 *
 * Real implementation of `pwr_on_arm_pl011`, copied verbatim from
 * zephyr-src/drivers/serial/uart_pl011.c (re-verified against that file during
 * preparation, Oct 2 2026), with only the `static` keyword stripped from this one
 * function so a separately-compiled harness.cpp can call it. Any other function it
 * depends on is embedded below exactly as the real driver wrote it, kept `static`
 * (internal to this translation unit only, exactly matching the real driver's own
 * linkage for those helpers).
 */
#include "pwr_on_arm_pl011.h"

/* Defines the mock_regs_ptr global declared `extern` in common_stubs.h. Exactly one
 * translation unit must define it; this .c file is always compiled alongside the
 * harness, so it is the natural, single place to do so. The LLM-authored harness.cpp
 * only needs to ASSIGN to it (mock_regs_ptr = &my_regs;) via the extern declaration it
 * already gets through common_stubs.h -- never declare or define it itself. */
volatile void *mock_regs_ptr;



int pwr_on_arm_pl011(const struct device *dev)
{
    return 0;
}
