/* Auto-generated by generate_target_files.py from target_definitions.py -- do not
 * hand-edit; edit target_definitions.py and re-run the generator instead.
 *
 * Forward declaration ONLY for `pwr_on_arm_pl011` (CCN 1). The real implementation is
 * compiled separately in pwr_on_arm_pl011.c and linked in -- the LLM synthesizing a harness
 * against this header must NOT define this function itself (see
 * PromptFactory.build_synthesis_prompt's `externally_linked` flag).
 */
#ifndef AEROHARNESS_ITEM2_PWR_ON_ARM_PL011_H_
#define AEROHARNESS_ITEM2_PWR_ON_ARM_PL011_H_

#include "common_stubs.h"

int pwr_on_arm_pl011(const struct device *dev);

#endif /* AEROHARNESS_ITEM2_PWR_ON_ARM_PL011_H_ */
